name: 'Deploy to AWS'
env:
  AWS_DEFAULT_REGION: eu-west-1
  AWS_ACCESS_KEY_ID: AKIAY34U24FAXEM7PF2E
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  CLOUDFRONT_DISTRIBUTION_ID: E18HXMB3YDSNLJ

on:
  workflow_dispatch:
  push:
    branches: [2022-03-updates]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to AWS
        run: rm -rf ./.git && aws s3 sync ./ s3://www.perryharlock.co.uk/ --delete  --region eu-west-2
      - name: Uncache
        run: aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
